### ISSUE TITLE
Compiler problem related to UIDevice.currentDevice calls. Help?

### ISSUE THREAD

**Issue by fouquet** [fouquet/RFAboutView-Swift#1]
There's a problem with lines 442 and 443 of RFAboutView.swift. If I declare them the following way:

``` swift
let iOSVersion = UIDevice.currentDevice().systemVersion as String
let device =  UIDevice.currentDevice().model as String
```

the compiler bugs out compiling the file. It doesn't show me an error in the IDE (tried both Xcode and AppCode), but it just won't compile. I get the following error:

```
Global variable initializer type does not match global variable type!
%struct._class_t** @"\01L_OBJC_CLASSLIST_REFERENCES_$_"
LLVM ERROR: Broken module found, compilation aborted!
```

No idea what the issue is. The code works great outside RFAboutView.swift, so it's apparently not syntax related. I don't know if this is a compiler bug, or there's just something screwed up on my machine, but I just can't fix it. Maybe someone has some insight in this. Thanks!

Until this compiles on my machine these variables will stay empty, unfortunately :(

**Comment by kubbing** [comment]
facing the same issue (in another project), is there a solution?

**Comment by kubbing** [comment]
Found the issue, I used this in the same file. I guess it might be broken C makro in swift UIDevice header. I advice to use the proper `UIDevice.currentDevice()` only :P

```
if (UI_USER_INTERFACE_IDIOM() == .Pad) {
    navController.modalPresentationStyle = .FormSheet;
}
```

**Comment by fouquet** [comment]
While that was not my issue (I'm not using userInterfaceIdiom) your post did cause me to revisit this problem. Seems like something changed in the last Xcode version and it's compiling fine now. The more you know.
