### ISSUE TITLE
Allow manual additions to acknowledgements

### ISSUE THREAD

**Issue by ghodsfry** [fouquet/RFAboutView-Swift#10]
As a feature request:

The convenient Acknowledgements.plist file from cocoapods is a nice touch.
However, many of our projects use a combination of pods and other sources. That leaves us to manually modify the .plist file or modify the private function reformatAcknowledgementsDictionary to devise a custom solution (cannot override the function as it is marked private. We could also just extend or replace the acknowledgements class var but it, too, is private.)

Would it be possible to extend the API a bit to allow taking a dictionary of manually generated acknowledgements to append to the end of the automatically generated details?

**Comment by fouquet** [comment]
Yeah, I've stumbled across this as well. I'll come up with a solution, but it may take a couple of days. Very busy right now.

**Comment by ghodsfry** [comment]
Excellent. No worries on timing!

I would think something like:
    /// File name of a manually generated addendum acknowledgements plist _without_ extension. Defaults to "AcknowledgementsAddendum". Will be appended to contents of acknowledgementsFilename.
    public var acknowledgementsAddendumFilename: String = "ManualAcknowledgementsAddendum" 

```
public override func loadView() {
```

[...]
        if let ackFile = NSBundle.mainBundle().pathForResource(self.acknowledgementsFilename, ofType: "plist") {
            let dict = NSDictionary(contentsOfFile: ackFile)
            self.acknowledgements = self.reformatAcknowledgementsDictionary(dict)
        }
        if let ackAddendumFile = NSBundle.mainBundle().pathForResource(self.acknowledgementsAddendumFilename, ofType: "plist") {
            let dict = NSDictionary(contentsOfFile: ackAddendumFile)
            self.acknowledgements.update(dict)
        }
[...]

///http://stackoverflow.com/questions/24051904/how-do-you-add-a-dictionary-of-items-into-another-dictionary
extension Dictionary {
    mutating func update(other:Dictionary) {
        for (key,value) in other {
            self.updateValue(value, forKey:key)
        }
    }
}
....

Then perhaps include a sample ManualAcknowledgementsAddendum.plist file in the sample project as an easy template file.

**Comment by fouquet** [comment]
Not quite what you had in mind, I guess, but I've added a new public method, `addAcknowledgement`, that lets you add additional acknowledgements. It takes a title and a content as strings.

**Comment by yodasl** [comment]
I am afraid that the current solution is not working since when you provide a filename for the Pods, the following code is executed in:
```
open override func loadView() {
...
if let ackFile = Bundle.main.path(forResource: acknowledgementsFilename, ofType: "plist") {
    if let dict = NSDictionary(contentsOfFile: ackFile) {
        acknowledgements = reformatAcknowledgementsDictionary(dict)
    }
}
```

so even if you call:
```
open func addAcknowledgement(_ title: String, content: String) {
```
prior to displaying the VC it will be automatically wipe out with the code in loadView() which assign the array, where in fact you may want to consider doing:
```
acknowledgements = acknowledgements + reformatAcknowledgementsDictionary(dict)
```

which will be adding it to the previous ones added manually
