### ISSUE TITLE
Crash: Dictionary

### ISSUE THREAD

**Issue by petritz** [fouquet/RFAboutView-Swift#2]
I get this error:

```
fatal error: unexpectedly found nil while unwrapping an Optional value
```

On the following line: (in reformatAcknowledgementsDictionary)

``` swift
for innerDict: AnyObject in theDict {
/* -> */ outputArray.addObject(["title":innerDict["Title"] as! String,"content":innerDict["FooterText"] as! String])
}
//EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
//Cast from '[SKNODE]!' to unrelated type 'String' always fails
```

**Comment by fouquet** [comment]
Yeah, didn't occur to me that the source plist may have different formatting ;-)

I'm now safe unwrapping these before adding them to the array.

**Comment by fouquet** [comment]
Yeah, didn't occur to me that the source plist may have different formatting ;-)

I'm now safe unwrapping these before adding them to the array. Thanks for reporting this :+1:
