### ISSUE TITLE
Crash Dictionary 2

### ISSUE THREAD

**Issue by petritz** [fouquet/RFAboutView-Swift#3]
Now I get this error:

```
1. EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
2. Cast from '[SKNODE]!' to unrelated type 'String' always fails
(fatal error: unexpectedly found nil while unwrapping an Optional value)
```

At this line:

``` swift
if tableView.tag == 0 {
      title = self.additionalButtons[indexPath.row]["title"] as! String //this is error 1
} else {
      title = self.acknowledgements[indexPath.row]["title"] as! String //this is error 2
}
```

I dont know if it is my Acknowledgement.plist, but If I put the original file in my project it does not work either. But your example works fine, and a new project I created is also working fine.

**Comment by fouquet** [comment]
Hm, I can't reproduce that. Could you post your acknowledgements.plist file? Or send it to mail [at] fouquet.me.

**Comment by petritz** [comment]
Yeah sure.

**Comment by petritz** [comment]
The error just occurs with all my files, I do not know why. I deleted everything except the classes for the AboutView and everything worked fine. I will just close it now.
